import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";

const prod = process.argv[2] === "production";

// docx bundles legacy IE schedulers internally, so module aliases cannot reach
// them. The branches are dead in Electron/Chromium. Replace their script nodes
// with inert elements and reject the obsolete string-callback form of
// setImmediate, then fail the build if dynamic code execution remains.
function sanitizeLegacyPolyfills() {
  let code = readFileSync("main.js", "utf8");

  const scriptElements = code.match(/createElement\((['"])script\1\)/g) ?? [];
  const stringCallbackPattern = /new Function\(\s*""\s*\+\s*[$A-Za-z_][$\w]*\s*\)/g;
  const stringCallbacks = code.match(stringCallbackPattern) ?? [];
  if (scriptElements.length !== 8 || stringCallbacks.length !== 2) {
    throw new Error(
      `Legacy polyfill signature changed: found ${scriptElements.length} script elements and ` +
      `${stringCallbacks.length} string callbacks; review dependencies before updating the sanitizer.`
    );
  }

  code = code.replace(/createElement\((['"])script\1\)/g, 'createElement("span")');
  code = code.replace(stringCallbackPattern, '(() => { throw new TypeError("String callbacks are not supported"); })');

  const forbidden = [
    [/createElement\((['"])script\1\)/, 'script element creation'],
    [/\beval\s*\(/, 'eval'],
    [/\b(?:new\s+)?Function\s*\(/, 'Function constructor'],
  ];
  for (const [pattern, label] of forbidden) {
    if (pattern.test(code)) throw new Error(`Unsafe ${label} remains in main.js`);
  }

  writeFileSync("main.js", code);
}

const shim = name => fileURLToPath(new URL(`./build-shims/${name}`, import.meta.url));

function loadSafeDocx(args) {
  let contents = readFileSync(args.path, "utf8");
  const dynamicBind = 'bound = Function("binder", "return function (" + joiny(boundArgs, ",") + "){ return binder.apply(this,arguments); }")(binder);';
  const dynamicGenerator = 'return Function("return function*() {}")();';
  const browserBase64 = 'return new Uint8Array(atob(dataURI.substring(base64IndexWithOffset)).split("").map((c) => c.charCodeAt(0)));';
  const dynamicIntrinsic = `var getEvalledConstructor = function(expressionSyntax) {
		try {
			return $Function("\\"use strict\\"; return (" + expressionSyntax + ").constructor;")();
		} catch (e) {}
	};`;

  if (!contents.includes(dynamicBind) || !contents.includes(dynamicGenerator) ||
      !contents.includes(dynamicIntrinsic) || !contents.includes(browserBase64)) {
    throw new Error("docx compatibility helpers changed; review the safe replacements before upgrading docx.");
  }

  // Preserving a bound function's exact `.length` is not required by docx.
  contents = contents.replace(dynamicBind, 'bound = function() { return binder.apply(this, arguments); };');
  contents = contents.replace(dynamicGenerator, 'return function*() {};');
  contents = contents.replace(dynamicIntrinsic, 'var getEvalledConstructor = function() {};');
  contents = contents.replace(
    browserBase64,
    'return Uint8Array.from(Buffer.from(dataURI.substring(base64IndexWithOffset), "base64"));',
  );
  return { contents, loader: "js" };
}

const context = await esbuild.context({
  banner: {
    js: "/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/",
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  plugins: [
    {
      name: "safe-legacy-dependencies",
      setup(build) {
        build.onResolve({ filter: /^underscore$/ }, () => ({ path: shim("underscore.cjs") }));
        build.onResolve({ filter: /^bluebird\/js\/release\/promise$/ }, () => ({ path: shim("bluebird-promise.cjs") }));
        build.onResolve({ filter: /^immediate$/ }, () => ({ path: shim("immediate.cjs") }));
        build.onResolve({ filter: /^setimmediate$/ }, () => ({ path: shim("setimmediate.cjs") }));
        build.onLoad(
          { filter: /[\\/]node_modules[\\/]docx[\\/]dist[\\/]index\.(?:cjs|mjs)$/ },
          loadSafeDocx,
        );
      },
    },
    {
      // dingbat-to-unicode is a 116 KB lookup table used by mammoth to convert
      // Wingdings/Symbol chars. mammoth falls back gracefully (emits a warning,
      // skips the character) when hex() returns null, so a stub is safe.
      name: "stub-dingbat-to-unicode",
      setup(build) {
        build.onResolve({ filter: /^dingbat-to-unicode$/ }, (args) => ({
          path: args.path,
          namespace: "dingbat-stub",
        }));
        build.onLoad({ filter: /.*/, namespace: "dingbat-stub" }, () => ({
          contents: "module.exports = { hex: () => null };",
          loader: "js",
        }));
      },
    },
    {
      name: "sanitize-legacy-polyfills",
      setup(build) {
        build.onEnd(() => sanitizeLegacyPolyfills());
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
